### PR TITLE
Add controling of first page for converting. Change max_page_count to last_page

### PR DESCRIPTION
**Pull request by minarth**
Add a parameter for selecting the first page of pdf document for converting. Changing the max_page_count to last_page to keep it logically named.

### CODE REVIEW

**Comment by minarth** [comment]
Oh, I missed the tests. I will repair it and then commit tested version.

**Comment by Belval** [comment]
Normally I would avoid breaking changes, but since 0.1.8 was released only a week ago and that max_page_count is not a real pdftoppm parameter your approach seems better.

**Comment by minarth** [comment]
@Belval It seems to be passing the test now.

**Comment by Belval** [comment]
@minarth Good job, I will create the new package later today.

**Pull request merged**
