### PR TITLE
Add use_pdftocairo parameter

### LINKED ISSUE #137: Can't work some pdf files
BAS16P11300049008_005-page-001
Hi..I have more than 100pdf files but it's not working I don't know how it's happening..I attached one of my pdf files..I used python 3.8 .can you give any suggestions?

### PR DESCRIPTION
**Pull request by Belval**
`pdftoppm` seems to be slower for complex PDFs. While I do not wish to make `pdftocairo` the default, it seems reasonable to allow people to do so.

Also, fixes #137

### CODE REVIEW

**Comment by zoj613** [comment]
Is there a reason why this new parameter is not available for the `convert_from_bytes` function?

**Comment by Belval** [comment]
Not normal at all, I'll make a emergency update. Thank you from bringing this to my attention.

**Comment by Belval** [comment]
Version 1.13.1 should be live. Version 1.13.0 was yanked from PyPi.

**Comment by zoj613** [comment]
> Version 1.13.1 should be live. Version 1.13.0 was yanked from PyPi.

thank you so much

**Pull request merged**
